### ISSUE TITLE
snx-rs-gui can't save settings if ~/.config/snx-rs dir does not exists

### ISSUE THREAD

**Issue by nxshock** [ancwrd1/snx-rs#28]
Steps to reproduce:
1. Remove ~/.config/snx-rs dir if it exists
2. Start snx-rs-gui
3. Open `Settings...` in context menu, fill data and press `OK` button
4. Open `Settigns...` again - all fields will be empty

System:
* Arch Linux
* snx-rs 2.2.4 from [AUR](https://aur.archlinux.org/packages/snx-rs)

**Comment by ancwrd1** [comment]
Thanks for reporting this, should be fixed now.
