### ISSUE TITLE
Error sending UDP request when connecting

### ISSUE THREAD

**Issue by ezinocin** [ancwrd1/snx-rs#41]
Hi, I was trying connecting to a server with Azure authentication but when i launch the `snxctl connect` command it returns me the following message:
![screen](https://github.com/user-attachments/assets/cedf02dc-2693-47c8-8c82-1813b9ae46d0)

I installed all the necessary packages, but i don't exclude that i lost something.

Can you help us resolve the issue?

![Screenshot_20240902_112627](https://github.com/user-attachments/assets/15cd5dcb-3521-4ea0-84a5-ffc7c993533d)
Kubuntu 23.04
KDE: 5.27.4
Kernel: 6.2.0-39-generic

![Screenshot_20240902_113044](https://github.com/user-attachments/assets/ea3495bb-7b73-402c-9a20-e30c2e238b6d)

**Comment by ancwrd1** [comment]
Hello, do you have snx-rs service running with "-m command" parameter?

**Comment by ancwrd1** [comment]
`snxctl` expects that there is a running service, which you should start with `sudo ./snx-rs -m command`. You can also install it as a systemd service, example unit file is included in the package.

**Comment by ancwrd1** [comment]
This error usually means that authentication failed (incorrect credentials).
You can try to enable the debug or trace log when running snx-rs service app, with `--log-level=trace` parameter (next to `-m command`).
There will be a lot of debug info dumped, along with requests and responses. There will be a sensitive data there though, so you could check it yourself first, or remove some texts.

**Comment by ezinocin** [comment]
Hi Dmitry,
the problem was that i'm using Azure as autenthication method filling username and password fields.
Those fields needs to be empty.

Now it is working fine, thank you!

**Comment by ancwrd1** [comment]
Ok great!

**Comment by ancwrd1** [comment]
I have added a fix to ignore the password for SAML authentications.
