### ISSUE TITLE
Error: failed to fill whole buffer

### ISSUE THREAD

**Issue by pgarroni-peernetwork** [ancwrd1/snx-rs#43]
Hi, i get this error when trying to connect:

```
~/dev/vpn/snx-rs-main/target/release ❯ ./snxctl connect                                                                                                                                            16:23:45
Error: failed to fill whole buffer

```

I've also tried to specify the configuration file with: `./snxctl connect -c ~/.config/snx-rs/snx-rs.conf` , but the error is the same. Also trying to connect via the gui with `./snx-rs-gui` results in the same error.
This is the configuration file `~/.config/snx-rs/snx-rs.conf`, the authentication needed is via Azure:

```
server-name=*omitted client IP*
user-name=
password=
search-domains=
ignore-search-domains=
default-route=false
no-routing=false
add-routes=
ignore-routes=
no-dns=false
no-cert-check=true
ignore-server-cert=true
ipsec-cert-check=false
tunnel-type=ipsec
ca-cert=
login-type=vpn_AzureAD
cert-type=none
no-keychain=false
server-prompt=true
esp-lifetime=3600
ike-lifetime=28800
ike-port=500
```

Do you have any idea what could be the cause?
Thank you very much for your help

**Comment by ancwrd1** [comment]
Hello, I have seen this issue with another user, this usually means your IPSec traffic is intercepted on your local network, for example by the router (QoS, DPI or similar), and the packets are modified.

**Comment by pgarroni-peernetwork** [comment]
I've tried connecting from my mobile's hotspot and now the connection works.
Thank you very much for your help, i'm closing the issue.
Have a nice day

**Comment by ancwrd1** [comment]
FYI, after some investigation I found out that the most probable reason is the firewall blocking fragmented UDP packets (bigger than MTU).
