### ISSUE TITLE
Add log-level settings to UI dialog, otherwise it is deleted when UI dialog is saved

### ISSUE THREAD

**Issue by qwertyuiopzxcvbnmlkjhgfdsa1** [ancwrd1/snx-rs#44]
Could there be added possibility to set `log-level` to UI dialog(question mark)  

I am facing situation, that `log-level=trace`  is deleted, when UI dialog set new properties values. Seems like config file is recreated - assume this is correct.

**Comment by ancwrd1** [comment]
It can be added but it currently doesn't make much sense because it will not be applied to the snx-rs service. When running in command mode, it expects a log-level parameter on the command line, the one received from the snxctl or from the GUI app is not used.
