### ISSUE TITLE
Support Multi-Factor Authentication with DynamicID

### ISSUE THREAD

**Issue by samtux** [ancwrd1/snx-rs#45]
Is it possible to use the multi-factor authentication connection option? Generally, this requires at the prompt to enter the username, password and a dynamic number sent to the email. 

https://sc1.checkpoint.com/documents/R81.20/WebAdminGuides/EN/CP_R81.20_MobileAccess_AdminGuide/Content/Topics-MABG/DynamicID.htm

the command used is:. 

`sudo snx-rs -X true -m standalone -s server.com.co --login-type vpn_VPN2FA --server-prompt true`

**Comment by ancwrd1** [comment]
It should work via the generic MFA support (you should get an MFA prompt for it).
Is there any error you are getting?

**Comment by samtux** [comment]
Thank you. It works with the following command, asking for the DynamicID

`sudo snx-rs -X true -m standalone -s host.com.co --login-type vpn_VPN2FA -u samtux --tunnel-type ssl`
