### ISSUE TITLE
Error: invalid type: sequence, expected path string at line 1 column 354.

### ISSUE THREAD

**Issue by Dennis-1978** [ancwrd1/snx-rs#48]
Hi!
I was using version 2.0.0 before the upgrade, I upgraded to 2.5.0 and started getting the following error: Error: invalid type: sequence, expected path string at line 1 column 354.
Can you tell me what could be the reason?

**Comment by ancwrd1** [comment]
Could you provide a bit more context: which authentication type and which tunnel type you use, how does a config file look like, ideally also trace-level log (with sensitive data stripped).

**Comment by Dennis-1978** [comment]
The snx-rs.conf configuration file:

server-name=
user-name=
password=
search-domains=
ignore-search-domains=
default-route=false
no-routing=false
add-routes=
ignore-routes=
no-dns=false
no-cert-check=false
ignore-server-cert=true
ipsec-cert-check=false
tunnel-type=ssl
ca-cert=
login-type=vpn_Indeed
cert-type=none
no-keychain=true
server-prompt=true
esp-lifetime=3600
ike-lifetime=28800
ike-port=500
ike-persist=false
log-level=off
client-mode=secure_connect
