### ISSUE TITLE
IPSEC leading to Error: No CCC session in reply!

### ISSUE THREAD

**Issue by leleobhz** [ancwrd1/snx-rs#57]
Hello!

I'm trying to connect to an endpoint in IPSEC mode and I got the error "No CCC session in reply!".

Server info:

```
$ snx-rs -m info -s <
Supported tunnel protocols:
        IPSec
        SSL
        L2TP
Available login types:
        vpn_SAML-Google (Login With Google)
        vpn (Standard)

``` 

Trace log (Redacted due sensitive information exposed): [snx-rs-ipsec-trace.txt](https://github.com/user-attachments/files/17982812/snx-rs-ipsec-trace.txt)

What is wrong with this connection? It works on SSL mode. Only IPSEC mode does have this issue. Also, company does have Office Mode licences.

Thanks!

**Comment by ancwrd1** [comment]
Hi, so we are sending the OM (office mode) request to the server which asks for several attributes, including IP address, DNS name and session ID.

The reply only contains one attribute, IP address, and it's empty (0.0.0.0):

```text
        Attributes(
            AttributesPayload {
                attributes_payload_type: Reply,
                identifier: 40382,
                attributes: [
                    DataAttribute {
                        attribute_type: 1,
                        value: Long(
                            b"\0\0\0\0",
                        ),
                    },
                ],
            },
        ),
```

I think it could be some configuration on the server side. I am not really sure. The common response is similar to this, which includes all the requested information:

```
        Attributes(
            AttributesPayload {
                attributes_payload_type: Reply,
                identifier: 40255,
                attributes: [
                    DataAttribute {
                        attribute_type: 1,
                        value: Long(
                            b"\n\0\x1ez",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 2,
                        value: Long(
                            b"\xff\xff\xfc\0",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 3,
                        value: Long(
                            b"\n\0\0c",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 3,
                        value: Long(
                            b"\n\0\0e",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 5,
                        value: Long(
                            b"\0\0p|",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 16387,
                        value: Long(
                            b"domain1.com,domain2.com",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 16453,
                        value: Long(
                            b"f8bb06d14665e46f2da9a286e36c9ad8\0\0\0\0\0\0\0\0\0",
                        ),
                    },
                ],
            },
        ),
    ],
```

**Comment by ancwrd1** [comment]
May be you could try with Google SAML login type?

**Comment by leleobhz** [comment]
> May be you could try with Google SAML login type?

Hello @ancwrd1 !

This setup is headless, so I'm unable to login it everytime token expires (My company expires each 12h). I have the permission to use user/password and using mode SSL it works (and its running like this now), but IPSEC does not.

This is somewhat related to auth? If it is, why works with SSL mode but not with IPSEC mode?

Thanks!

**Comment by ancwrd1** [comment]
You could perhaps try `--client-mode` parameter with different values: `endpoint_security` or `secure_remote`. The default is `secure_connect`.
Otherwise I am not sure what can be the issue, looks like the server does not assign an IP address to the client.

**Comment by leleobhz** [comment]
> You could perhaps try `--client-mode` parameter with different values: `endpoint_security` or `secure_remote`. The default is `secure_connect`.

Hello!

`endpoint_security` worked! What is the criteria to choose each one? There is any evidence on debug or trace that leads to this attempts or its a matter of try all or ask VPN owner for the parameter?

Thanks!

**Comment by ancwrd1** [comment]
Good question, I wasn't able to figure that out yet :)
So for now it's just try and see.

**Comment by leleobhz** [comment]
I have a weird behaviour: Sometimes it work, sometimes not. The moment it runned was when I have mode ssl connected in another machine on same network and run `endpoint_security` at my machine.

I'm trying to drilldown the issue properly to detect what is happening.

**Comment by leleobhz** [comment]
@ancwrd1 Feedback with close:

I confirmed with IT team of VPN target: Issue was office-mode and licencing: Checkpoint at the version they are using have a bug that locks unfinished sessions and counts as licence usage - even if the tunnel died. Old session only finishes if manually deleted on appliance or waiting 12h (Time the VPN reloads for anyone).

After session cleanup, VPN comes up normally! 

Thank you so much by you support here!

**Comment by leleobhz** [comment]
P.s: And `--client-mode` change was indeed necessary.

**Comment by ancwrd1** [comment]
Great, thanks for confirming. I will add it to the FAQ section.

**Comment by leleobhz** [comment]
Hello @ancwrd1 

Today I learned `No CCC session in reply!` error can also happen when CheckPoint Endpoint licences got exausted and sessions on Checkpoint got stuck.

Maybe a good one to add to FAQ

**Comment by ancwrd1** [comment]
Updated README, thanks.
