### ISSUE TITLE
An option to disable text in the notification area?

### ISSUE THREAD

**Issue by dark-penguin** [ancwrd1/snx-rs#59]
Hi!
Would it be possible to have an option to only display an icon and not the text in the notification area? Maybe text could just be in a tooltip. The text takes too much space, and it's not something you would usually have in there. I'm well aware that this icon represents the SNX VPN client, thank you very much. :slightly_smiling_face: 

![Screenshot at 2024-12-05 16-28-48](https://github.com/user-attachments/assets/d7c15279-fd9b-44a1-86e5-c31a8a214772)

**Comment by ancwrd1** [comment]
If you can build the project (instructions are provided in the README) try removing this line: https://github.com/ancwrd1/snx-rs/blob/main/snx-rs-gui%2Fsrc%2Ftray.rs#L48

**Comment by dark-penguin** [comment]
This helped, thanks! Should it maybe be a setting though?.. Or disabled by default, since really is anyone expecting text in system tray?

**Comment by ancwrd1** [comment]
I will remove it.

**Comment by ancwrd1** [comment]
It's not displayed in KDE or GNOME desktop though.

**Comment by dark-penguin** [comment]
Notification areas in Linux are complete bacchanalia. :slightly_smiling_face: My last battle with them was when I was helping fix "minimize to tray" functionality in Betterbird. It was a sight to behold. :smile:
