### ISSUE TITLE
Wrong text in the MFA windows if the password is saved

### ISSUE THREAD

**Issue by dark-penguin** [ancwrd1/snx-rs#60]
If I don't save my password, then after connecting, I get the first window asking for the password, and then the second window asking for the MFA security code.
![1-password](https://github.com/user-attachments/assets/4dfa51d7-6258-4157-9d3d-6dce4dd7eff0)
![2-challenge](https://github.com/user-attachments/assets/e1234a3c-17c0-4ff2-863c-3fdbb6eb2124)

But if I DO save my password in the "Settings", then after connecting, I get one window asking for the PASSWORD!, but it actually expects the security code.
![1-password](https://github.com/user-attachments/assets/4dfa51d7-6258-4157-9d3d-6dce4dd7eff0)

**Comment by ancwrd1** [comment]
Try disabling the option to get MFA prompts from the server (server-prompt=false).

**Comment by ancwrd1** [comment]
So the difference is, with the server-prompt option enabled, it will fetch the prompts from the VPN server using http call (same call is used to get login types).
With this option disabled, the prompts are provided in the MFA replies.
You would normally expect them to match the ones returned in the http discovery call, but there is nothing consistent in checkpoint products and its just a big mess.
Anyway, I will try to fix it.

**Comment by ancwrd1** [comment]
Should be fixed now

**Comment by dark-penguin** [comment]
Oh, so both of those are requested from the server! I thought one of them was to "not ask the server, use hard-coded captions instead".

So which one is which? I suppose "Ask the server" means "ask for captions in advance via HTTP", and disabling it means "Only use what the server provides during negotiaton"? I wonder if there's a better way to phrase it...

**Comment by ancwrd1** [comment]
That's correct, yes.

**Comment by dark-penguin** [comment]
Got it, thanks!
