### ISSUE TITLE
NixOS is using a two level symliink to /etc/resolv.conf

### ISSUE THREAD

**Issue by denisfalqueto** [ancwrd1/snx-rs#62]
For some crazy reason, NixOS is using a double symlink to /etc/resolv.conf:

/etc/resolv.conf -> /etc/static/resolv.conf -> /run/systemd/resolve/stub-resolv.conf

For this reason, the detection of systemd-resolved in src/platform/linux/resolver.rs is being misled to act as if a normal /etc/resolv.conf was being used.

Would you be willing to accept a pull request to change the strategy, so the code tries to follow the links (until a predefined number of hoops)? I have this ready, if you want.

Thank you so much for your work!

**Comment by ancwrd1** [comment]
Sure, go for it!

**Comment by ancwrd1** [comment]
Fixed in 1257b12693a25f1dfe1d9f0ca5dbf87ff2d0289d
