### ISSUE TITLE
After suspend, connection is not dropped but does not work

### ISSUE THREAD

**Issue by dark-penguin** [ancwrd1/snx-rs#64]
Hi!
After you suspend/hibernate and then resume, the connection is still there - both the network interface and the GUI icon. But, naturally, it does not work, since even the local connection gets dropped and recreated.

The fix is to simply reconnect again, but should't it at least detect this (momentary absence of the default route, or the "underlying" route to the VPN host, I guess?) and disconnect (and remember to update the icon)?

**Comment by ancwrd1** [comment]
It should work after suspend/resume, at least IPSec tunnel, it's been working for me since day 1. IPSec has it's own state machine and it tunneled via UDP, so the state of the underlying connection does not matter. For SSL tunnel it may require a reconnection, yes.

**Comment by ancwrd1** [comment]
Anyway, for both tunnels, there is a keepalive logic which will disconnect them when keepalive packets get no reply.

**Comment by dark-penguin** [comment]
I'm using SSL. How long should I wait for it to notice that keepalives aren't arriving? I've tried to wait a little, but it did not disconnect after quite some time.

**Comment by ancwrd1** [comment]
For SSL tunnel the default is 3 keepalive attempts, and the interval between them is sent by the server's hello reply, it is usually 20 seconds. I am wondering if it's higher value in your case.
You could check it in the trace-level logs, it looks like:

```
Hello reply: HelloReplyData { version: 1, protocol_version: 1, ... timeouts: Timeouts { authentication: 259193, keepalive: 20 } ... }
```

If it's still 20, could be a bug in the code, you should see the trace-level entries like:

```
Keepalive request: KeepaliveRequestData { id: "0" }
Control packet received
```

**Comment by ancwrd1** [comment]
Also please note that keepalive is paused when NetworkManager is not in the `ConnectedGlobal` state.

**Comment by dark-penguin** [comment]
```
Dec 11 17:23:10 MSI snx-rs[168226]: 2024-12-11T13:23:10.750130Z DEBUG snxcore::tunnel::ssl::connector: Tunnel connected
Dec 11 17:23:10 MSI snx-rs[168226]: 2024-12-11T13:23:10.904910Z DEBUG snxcore::tunnel::ssl: Control packet received
Dec 11 17:23:30 MSI snx-rs[168226]: 2024-12-11T13:23:30.826335Z DEBUG snxcore::tunnel::ssl: Control packet received
Dec 11 17:23:49 MSI snx-rs[168226]: 2024-12-11T13:23:49.847685Z DEBUG snxcore::platform::linux::net: NetworkManager state changed to Asleep
Dec 11 17:25:34 MSI snx-rs[168226]: 2024-12-11T13:25:34.147626Z DEBUG snxcore::platform::linux::net: NetworkManager state changed to ConnectedLocal
Dec 11 17:25:37 MSI snx-rs[168226]: 2024-12-11T13:25:37.671923Z DEBUG snxcore::platform::linux::net: NetworkManager state changed to Connecting
Dec 11 17:25:39 MSI snx-rs[168226]: 2024-12-11T13:25:39.698926Z DEBUG snxcore::platform::linux::net: NetworkManager state changed to ConnectedSite
Dec 11 17:25:39 MSI snx-rs[168226]: 2024-12-11T13:25:39.699405Z DEBUG snxcore::platform::linux::net: NetworkManager state changed to ConnectedGlobal
Dec 11 17:25:53 MSI snx-rs[168226]: 2024-12-11T13:25:53.938911Z DEBUG snxcore::tunnel::ssl: Control packet received
Dec 11 17:26:13 MSI snx-rs[168226]: 2024-12-11T13:26:13.976000Z DEBUG snxcore::tunnel::ssl: Control packet received
Dec 11 17:26:33 MSI snx-rs[168226]: 2024-12-11T13:26:33.967574Z DEBUG snxcore::tunnel::ssl: Control packet received
```
...But there is no actual connectivity through the VPN - I'm trying to ping a host, and I can't even resolve it. (The routes and DNS domains in resolvectl are still there.)

**Comment by dark-penguin** [comment]
Actually, no, it seems to work now for some reason...

**Comment by ancwrd1** [comment]
Could be related to a systemd-resolved bug: https://github.com/systemd/systemd/issues/21123

I have never seen it though on my machine.

**Comment by dark-penguin** [comment]
Probably. I had it not pinging before, but now it works immediately after resume. This is even better than what I had with OpenVPN NetworkManager plugin before! :star_struck:

**Comment by ancwrd1** [comment]
Hey, can this issue be closed? Or you still have some problems with suspend?

**Comment by dark-penguin** [comment]
Seems fine!
